### ISSUE TITLE
add my profile to snakemake-profiles

### ISSUE THREAD

**Issue by SilasK** [Snakemake-Profiles/doc#10]
I created a profile mainly for slurm, but it acn be adapted to other cluster systems. 

https://github.com/SilasK/adaptable_profile

**Comment by johanneskoester** [comment]
Nice! Ideally, there would be a unit test as well, but other profiles in here don't have it either, so I think it should be fine to move it here. Do you prefer me to fork or do you want to move it here? In addition, I think it won't hurt to clean it up a bit, add some more comments and remove some commented out snippets. However, this can be done after moving whenever you or somebody else feels like.

**Comment by SilasK** [comment]
Hey Johannes Köster

I cleaned the code a bit. For unit test I would need a docker implementation of a cloud system isn’t it?
How can I move it to the repo?

**Comment by johanneskoester** [comment]
Unit testing should happen via travis ci. You should be able to  setup e.g. a slurm cluster within travis ci via https://github.com/giovtorres/slurm-docker-cluster.

For moving, you need to go to settings and transfer ownership to the snakemake-profiles organization.

**Comment by johanneskoester** [comment]
Before moving, what do you think about renaming the repo to `generic`? Feels more in line with the other profile names, i.e., `slurm`, `pbs-torque`, `generic`.

**Comment by SilasK** [comment]
Done

**Comment by SilasK** [comment]
I would agree to move my repro to the snakemake profile user, as described in #4 , If I can continue having access.

**Comment by johanneskoester** [comment]
Yes, of course, once you did the move, I will give you write access.

**Comment by SilasK** [comment]
What do I have to do exactly?

**Comment by johanneskoester** [comment]
In your repo, go to settings and there to transfer ownership. Then you enter snakemake-workflows as the new owner.

**Comment by SilasK** [comment]
Unfortunately, I get errors that I don’t have the right to create repositories neither in snakemake-workflows nor in snakemake-profiles. What can I do?

**Comment by johanneskoester** [comment]
I have invited you to both organizations. Now it should hopefully work?
