### ISSUE TITLE
Include LSF profile

### ISSUE THREAD

**Issue by mbhall88** [Snakemake-Profiles/doc#12]
I have made an LSF profile: https://github.com/mbhall88/snakemake-lsf

I have tested it on our cluster with a couple of pipelines and it seems to be working. But if you have suggestions of how I can make proper tests that would be great. I saw the slurm repo has a pretty extensive test suite...

**Comment by johanneskoester** [comment]
Great! So for testing, the ideal scenario would be to have a CI setup that executes an ad-hoc LSF cluster (e.g. via docker) to which we would automatically submit a few toy jobs. I am not sure whether such container images are available though.

**Comment by johanneskoester** [comment]
In any case, we can include it now, it looks very good. Do you want to move it to snakemake-profiles (via github settings), or do you want me to fork it? In any case, I would of course grant you the ownership of the repo.

**Comment by mbhall88** [comment]
> Great! So for testing, the ideal scenario would be to have a CI setup that executes an ad-hoc LSF cluster (e.g. via docker) to which we would automatically submit a few toy jobs. I am not sure whether such container images are available though.

Ok cool. I will see if I can set something like this up. Maybe I will create a separate issue where I/we can work on this? Not having done this before it would be great to get some guidance.

> In any case, we can include it now, it looks very good. Do you want to move it to snakemake-profiles (via github settings), or do you want me to fork it? In any case, I would of course grant you the ownership of the repo.

Whichever method you think is best for integrating with the rest of the profiles/community?

**Comment by johanneskoester** [comment]
I would prefer the move. This way, we do not risk that the two instances accidentally diverge again.

**Comment by johanneskoester** [comment]
The move has to be done by you.

**Comment by mbhall88** [comment]
Ok, I will move it then. Your invitation to add me as a collaborator was cancelled, so I can't make the transfer until I am added to Snakemake-Profiles...

**Comment by johanneskoester** [comment]
Sorry, I have renewed the invitation.

**Comment by johanneskoester** [comment]
Thanks for moving! I have added it to the docs.
