### ISSUE TITLE
HTCondor profile for review

### ISSUE THREAD

**Issue by jheuel** [Snakemake-Profiles/doc#15]
I wrote a profile for submitting jobs to HTCondor clusters:
https://github.com/jheuel/htcondor

**Comment by johanneskoester** [comment]
Awesome! Can we move it here? Or do you prefer me to fork it?

**Comment by johanneskoester** [comment]
Both would be fine.

**Comment by jheuel** [comment]
We can move it

**Comment by johanneskoester** [comment]
Great. I have sent you an invitation to the organization. After you have accepted it, you should be able to move your repo to this organization via the settings.

**Comment by jheuel** [comment]
Done. I also created a pull request to add the repository to the doc/Readme
