### ISSUE TITLE
slurm profile for code review

### ISSUE THREAD

**Issue by percyfal** [Snakemake-Profiles/doc#2]
Hi,

I have written a profile for SLURM: https://github.com/percyfal/slurm. The repo shoud follow your guidelines. In addition, there is also code for test-driven development, in which a slurm and snakemake container can be run in docker swarm mode for easy testing.

Cheers,

Per

**Comment by percyfal** [comment]
I just saw the download url is incorrect and I have updated in percyfal/slurm.

**Comment by johanneskoester** [comment]
Thanks. I have also created an invitation for write access to your account.
