### ISSUE TITLE
Request profile inclusion: (Sun) Grid Engine

### ISSUE THREAD

**Issue by drjbarker** [Snakemake-Profiles/doc#22]
I've written a reasonably comprehensive snakemake profile for sun grid engine, please could it be reviewed and forked into the Snakemake-Profiles repo?

[snakemake-gridengine/cookiecutter](/drjbarker/snakemake-gridengine/tree/cookiecutter)

**Comment by johanneskoester** [comment]
Thank you so much! Looks good to me. I've forked it.

**Comment by johanneskoester** [comment]
I have send you an invitation for becoming a maintainer for the profile.

**Comment by drjbarker** [comment]
Thanks for forking and thanks for snakemake! It's replaced a spaghetti of bash scripting for me.
