### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mschubert** [Snakemake-Profiles/doc#4]
I just tried installing the *slurm* profile using the instructions provided, and it seems just using cookiecutter on the repository is not sufficient to have snakemake find it (and I think this is more general than just for slurm).

It would be great if you could add some general installation instructions here, like:

```
cd ~/.config/snakemake
cookiecutter <repo name>
```

**Comment by johanneskoester** [comment]
Yes, this is missing, you are right.

**Comment by johanneskoester** [comment]
Done.

**Comment by mschubert** [comment]
In this case, I meant adding them to this (the *doc*) repository, because

> The profile has to be installabile via cookiecutter.

is already in the guidelines and hence all repositories should be installable the same way.
