### ISSUE TITLE
Rate limit for cluster submissions

### ISSUE THREAD

**Issue by mschubert** [Snakemake-Profiles/doc#7]
For cluster submissions (which most repositories are about), it would be nice if there was a way to rate-limit submissions in addition to defining the maximum number of jobs.

This could be:

```yaml
resources:
    n_per_min: 30 # rate: <human readable rate> would be even better
```

The reason for this is that one of the limiting factors is bandwidth of network-mounted storage.

If I have 1000 jobs I want to run that take 24h each, starting them with `-j1000` would kill the file system and starting them with `-j50` would take 20 times as long.

**Comment by johanneskoester** [comment]
This is already possible: `--max-jobs-per-second`

**Comment by johanneskoester** [comment]
See [here](https://github.com/Snakemake-Profiles/surfsara-grid/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/config.yaml) for an example how to use that command line option in a profile.

**Comment by mschubert** [comment]
Thank you, I missed that before.
